fitmate/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  namespace :organizer do
    resources :events, only: %i[new create edit update]
  end
  resources :events, only: %i[index show] do
    resources :event_participants, only: %i[new create update]
    delete "/event_participants/:id", to: "event_participants#destroy", as: :delete_participation
    resources :chatboxes, only: %i[show] do
      resources :messages, only: %i[create]
    end
  end
  resources :users, only: %i[show]
end

# get "restaurants/:id", to: "restaurants#show", as: :restaurant
# delete "/events/:event_id/event_participants/:id", to:"event_participants#destroy", as: :delete_participation
# delete "/event_participants/:id", to: "event_participants#destroy", as: :delete_participation

fitmate/app/models/event.rb
class Event < ApplicationRecord
  belongs_to :organizer, class_name: "User"
  has_many :event_participants
  has_many :users, through: :event_participants
  has_one_attached :photo

  validates :sport, inclusion: { in: Sport::LIST }
  validates :title, presence: true
  validates :description, length: { maximum: 800 }, presence: true
  validates :localisation, presence: true
  validates :event_level, inclusion: { in: %w(débutant intermediaire expert), message: "%{value} n'est pas valide" }
  validates :max_participant, inclusion: { in: (1..25) }
  validates :datetime, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_sport_and_localisation,
    against: %i[sport localisation],
    using: {
    tsearch: { prefix: true }
    }

  geocoded_by :localisation
  after_validation :geocode, if: :will_save_change_to_localisation?


end

fitmate/app/controllers/events_controller.rb
require 'open-uri'
require 'nokogiri'

class EventsController < ApplicationController
  before_action :authenticate_user!

  def index
    @events = Event.all
    @sports = Sport::LIST
    @selected_sports = Sport::LIST.map(&:to_s)
    if params[:query].present?
      @events = @events.where("sport ILIKE ? OR localisation ILIKE ?", "%#{params[:query]}%", "%#{params[:query]}%")
    end
    @markers = @events.geocoded.map do |event|
      {
        lat: event.latitude,
        lng: event.longitude,
        marker_html: render_to_string(partial: "marker", locals: { event: event })
      }
    end
  end

  def show
    @event = Event.find(params[:id])
    @organizer = @event.organizer
    @event_participant = EventParticipant.where(event_id: params[:id], user_id: current_user)
    @sports = Sport::LIST
    # url = "https://portail.sportsregions.fr/#{@event.sport}/loire-atlantique/annuaire-clubs-de-#{@event.sport}-en-loire-atlantique"
    # doc = Nokogiri::HTML.parse(URI.open(url).read, nil, "utf-8")

    # @list_club = []

    # doc.search(".association").first(10).each do |element|
    #   club = {}
    #   club["name"] = element.search("h2").text.strip
    #   club["localisation"] = element.search("span > span").last.text.strip
    #   @list_club << club
    # end
  end

end

fitmate/app/controllers/organizer/events_controller.rb
module Organizer
  class EventsController < ApplicationController
    def new
      @event = Event.new
    end

    def create
      @event = Event.new(organizer_params)
      @event.organizer = current_user
      if @event.save
        redirect_to event_path(@event), notice: "Event added ✔️"
      else
        render :new, status: :unprocessable_entity
      end
    end

    private

    def organizer_params
      params.require(:event).permit(:title, :description, :localisation,
                                    :event_level, :max_participant, :datetime, :sport, :photo)
    end
  end
end

fitmate/app/views/organizer/events/new.html.erb
<%# ADD-EVENT %>
<div class="event-wrapper page-container">
  <%# LINK-TITLE-EVENT %>
  <div class="link-title-add-event">
    <%= link_to events_path do %>
      <div class="fitmate-header-navbar">
        <button class='transparent-button'>
          <i class="fa-solid fa-chevron-left" style="color: #f6d0a5;"></i>
        </button>
      </div>
    <% end %>

    <%# TITLE %>
    <div class="title-event-creation">
      <h3>Créer un évènement</h3>
    </div>

    <%# AVATAR USER %>
    <div class="avatar-user">
      <%= link_to user_path(current_user) do %>
        <%= cl_image_tag current_user.photo.key, width:45, height:45, class:"avatar-event"%>
      <% end %>
    </div>
  </div>

    <%# FORM %>
    <div class= "form-new-events">
      <%= simple_form_for([:organizer, @event]) do |f| %>

        <%# SPORT SELECT %>
        <div class="sport-selection">
          <div class="dropdown sport-event">
                <%= f.input :sport, label: "Sport",
                  as: :radio_buttons,
                  collection_wrapper_tag: 'div',
                  collection_wrapper_class: 'category-wrapper',
                  item_wrapper_class: 'category-item',
                  input_html: {class: 'category-selector'},
                  collection: Sport::LIST%>
          </div>
        </div>

        <%# DATE %>
        <div class= "select-date">
          <%= f.input :datetime, as: :string, label: "Date",
            input_html: { data: { controller: "flatpickr" } }
          %>
        </div>

        <%# LOCAL %>
        <div class= "localisation-event">
          <%= f.input :localisation, label: "Adresse",
                      input_html: { data: {address_autocomplete_target: "address"},
                                    class: "d-none",
                                    placeholder: "Nouveau placeholder"},
                      wrapper_html: {data: {controller: "address-autocomplete",
                                    address_autocomplete_api_key_value: ENV["MAPBOX_API_FIT_MATE"]}}
          %>
        </div>

        <%# LEVEL %>
        <div class="event-level">
          <%= f.input :event_level, label: "Niveau", collection: ['débutant', 'intermediaire', 'expert'], as: :radio_buttons%>
        </div>

        <%# PARTICIPANTS %>
        <div class="max-participant-event">
          <%= f.input :max_participant, label: "Nbr de participant", placeholder: "1 à 25" %>
        </div>

        <%# TITLE %>
        <div class="title-event">
          <%= f.input :title, label: "Titre de l'évènement", placeholder: "Séance de yoga..." %>
        </div>

        <%# DESCRIPTION %>
        <div class="description-event">
          <%= f.input :description, label: "Description", placeholder: "...maximum 800 caractères"%>
        </div>

        <%# IMG %>
        <div class="photo-event">
          <%= f.input :photo, as: :file%>
        </div>

        <%# CTA %>
        <%= f.submit "Ajouter", class: "btn-signin btn-create-event"%>
      <% end %>
    </div>

</div>