animals_rent/config/routes.rb
Rails.application.routes.draw do
  devise_for :users # ne pas supprimer
  root to: "pages#home"
  namespace :owner do
    get 'bookings/accept'
    get 'bookings/decline'
    resources :animals
    resources :bookings, only: [] do
      member do
        patch :accept
        patch :decline
      end
    end
  end
  resources :animals, only: %i[index show] do
    resources :bookings, only: %i[create edit update]
  end
  resources :bookings, only: %i[index]
end

animals_rent/app/models/animal.rb
class Animal < ApplicationRecord
  belongs_to :owner, class_name: "User"
  validates :name, presence: true
  validates :price_per_day, presence: true
  validates :localisation, presence: true
  validates :summary, length: { maximum: 1000 }
  has_one_attached :photo
  include PgSearch::Model
  pg_search_scope :search_by_name_and_summary,
                  against: %i[name summary],
                  using: {
                    tsearch: { prefix: true }
                  }
end

animals_rent/app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :animal
  validates :start_date, comparison: { less_than_or_equal_to: :end_date }, presence: true
  validates :end_date, comparison: { greater_than_or_equal_to: :start_date }, presence: true
end

animals_rent/app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
end

animals_rent/app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show] # buddy: write your skip

  def index
    @animals = Animal.all
    if params[:query].present?
      @animals = @animals.where("name ILIKE ? OR summary ILIKE ?", "%#{params[:query]}%", "%#{params[:query]}%")
    end
  end

  def show
    @animal = Animal.find(params[:id])
    @booking = Booking.new

  end

  private

  # def animal_params
  #   params.require(:animal).permit(:name, :price_per_day, :localisation, :can_swim, :can_walk, :can_fly, :summary, :poster_url)
  # end
end

animals_rent/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

animals_rent/app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # méthodes à créer/compléter : index, create, edit, update
  # méthode à créer/compléter mais route inexistante : new
  # skip_before_action :authenticate_user!

  def index
    @all_bookings = Booking.all
    @user_bookings = Booking.where(user_id: current_user.id)
    @owner_bookings = Booking.includes(:animal).where(animal: { owner_id: current_user.id })
    @animal = Animal.new
  end

  def create
    @animal = Animal.find(params[:animal_id])
    @booking = Booking.new(booking_params)
    @booking.animal = @animal
    @booking.user = current_user
    # @booking.total_price = (@booking.end_date - @booking.start_date) * @animal.price_per_day
    if @booking.save
      redirect_to bookings_path, notice: "Booking save"
    else
      render 'animals/show', status: :unprocessable_entity
    end
  end

  def edit
    @booking = booking.find(params[:id])
  end

  def update
    if @booking.update(booking_params)
      redirect_to accept_owner_booking_path(@booking)
    else
      redirect_to decline_owner_booking(@booking)
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :total_price, :status, :create_at, :updated_at, :user_id, :animal_id)
  end
end

animals_rent/app/controllers/owner/animals_controller.rb
module Owner
  class AnimalsController < ApplicationController
    # skip_before_action :authenticate_user!

    def index
      @animals = Animal.all
    end

    def new
      @animal = Animal.new
    end

    def show
      @animal = Animal.find(params[:id])
    end

    def create
      @animal = Animal.new(owner_params)
      @animal.owner = current_user
      # @booking.total_price = (@booking.end_date - @booking.start_date) * @animal.price_per_day
      if @animal.save
        redirect_to animal_path(@animal), notice: "Beast adding ✔️"
      else
        render 'animals/index', status: :unprocessable_entity
      end
    end

    private

    def owner_params
      params.require(:animal).permit(:name, :price_per_day, :localisation, :can_swim, :can_walk, :can_fly, :summary, :photo)
    end
  end
end

animals_rent/app/controllers/owner/bookings_controller.rb
class Owner::BookingsController < ApplicationController
  # skip_before_action :authenticate_user!

  def accept
    @booking = Booking.find(params[:id]) # va chercher le booking_id
    @booking.status = "accepted" # on a l'id, je modifie le status de booking en lui assignant la valeur "accept"
    @booking.save # je save le nouveau status
    redirect_to bookings_path # et je redirect vers l'index de booking
  end

  def decline
    @booking = Booking.find(params[:id]) # va chercher le booking_id
    @booking.status = "declined" # on a l'id, je modifie le status de booking en lui assignant la valeur "decline"
    @booking.save # je save le nouveau status
    redirect_to bookings_path # et je redirect vers l'index de booking
  end
end

animals_rent/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[home] # buddy: write your skip

  def home
  end
end

animals_rent/app/views/bookings/index.html.erb
<div class="bookings-global-container row">
  <h1 id="bookings-main-title">My dashboard</h1>
  <div class="col-received col-md-6"> <!-- 1ERE COLONNE -->
    <div class="titles-style"> <!-- TITLES -->
      <h1>Rental requests received</h1>
      <p>These people want to book one of your animals! Answer them:</p>
    </div> <!-- FIN TITLES -->
    <% @owner_bookings.each do |booking| %> <!-- ITERATION CARD AUTOMATIQUE-->
      <div class="booking-card"> <!-- BOOKING RECEIVED CARD -->
        <div class="row"> <!-- card row-->
          <div class="booking-card-box-one col-md-4"> <!-- renter profile -->
            <p><%= cl_image_tag booking.user.avatar.key, class:"booking-profile-photo"%></p>
            <p id="booking-profile-name"><%= booking.user.username %></p>
            <p id="booking-profile-age"><%= booking.user.age %> y/o</p>
            <p id="booking-profile-job">Passionate about <%= booking.user.job %></p>
          </div> <!-- fin renter profile -->
          <div class="reservation-container col-md-8">
            <div class="booking-card-box-two">
              <p id="wants-phrase"> <em><%= booking.user.username %></em> wants to rent <em><%= booking.animal.name %> </em><%= cl_image_tag booking.animal.photo.key, class:"booking-animal-photo-received"%></p>
              <div class="booking-date-request">
                <p> <img src="https://cdn-icons-png.flaticon.com/512/123/123392.png?w=1380&t=st=1685540969~exp=1685541569~hmac=2941c188814385158d9c3ad1b8fd230d8e9ac38e604193cf245f9d4eb6bf669a" alt="icone calendar" class="booking-icon"></p>
                <p>From <%= booking.start_date %> to <%= booking.end_date %></p>
              </div>
            </div> <!-- fin réservation détails -->
            <div class="booking-card-box-two">
            <% if booking.status.nil? %>
              <p>Booking pending </p>
                <div class="btn-booking">
                  <%= link_to 'Accept', accept_owner_booking_path(booking), data: {turbo_method: :patch} %>
                  <%= link_to 'Decline', decline_owner_booking_path(booking), data: {turbo_method: :patch} %>
                </div>
                <% elsif booking.status == "accepted" %>
                  <p>Booking accepted </p>
                <% else booking.status == "declined" %>
                  <p>Booking declined</p>
                <% end %>
            </div> <!-- fin réservation acceptance -->
          </div> <!-- fin réservation container -->
        </div> <!-- fin card row-->
      </div> <!-- FIN BOOKING RECEIVED CARD -->
    <% end %> <!-- FIN ITERATION CARD AUTOMATIQUE-->
  </div> <!-- FIN 1ERE COLONNE -->

  <div class="col-sent col-md-6"> <!-- 2E COLONNE -->
    <div class="titles-style"> <!-- TITLES -->
      <h1 class="titles-card booking-title text-center">Bookings demands sent</h1>
      <p class="titles-card booking-subtitle text-center">The animals you want to book :</p>
    </div> <!-- FIN TITLES -->
    <% @user_bookings.each do |booking| %> <!-- ITERATION CARD AUTOMATIQUE-->
      <div class="booking-card"> <!-- BOOKING SENT CARD -->

        <div class="row w-100"> <!-- card row-->

          <div class="booking-card-box-one col-md-4"> <!-- animal profile -->
            <%# <img src="" alt="" class="booking-profile-photo"> %>
            <p><%= cl_image_tag booking.animal.photo.key, class:"booking-animal-photo"%></p>
            <p class="booking-animal-name"><%= booking.animal.name %></p>
            <p class="booking-profile-price-per-day">$ <%= booking.animal.price_per_day.to_i %></p>

            <div class="icon-capacity-beast">
              <% if @animal.can_fly %>
              <%= image_tag("can_fly_2.png") %>
              <% end %>
              <% if @animal.can_walk %>
              <%= image_tag("can_walk_2.png") %>
              <% end %>
              <% if @animal.can_swim %>
              <%= image_tag("can_swim_2.png") %>
              <% end %>
            </div>

          </div> <!-- fin animal profile -->

          <div class="booking-details-container col-md-8">

            <div class="booking-card-box-two">

              <div class="booking-date-info">
                <p>You wants to rent <%= booking.animal.name %></p>
              </div>

              <div class="booking-date-request">
                <p> <img src="https://cdn-icons-png.flaticon.com/512/123/123392.png?w=1380&t=st=1685540969~exp=1685541569~hmac=2941c188814385158d9c3ad1b8fd230d8e9ac38e604193cf245f9d4eb6bf669a" alt="icone calendar" class="booking-icon"></p>
                <p>From <%= booking.start_date %> to <%= booking.end_date %></p>
              </div>

            </div> <!-- fin owner-informations -->

            <div class="booking-card-box-two">
              <p>Booking is pending ⏰</p>
            </div> <!-- fin booking status -->

          </div> <!-- fin booking details container -->
        </div> <!-- fin card row-->
      </div> <!-- FIN BOOKING SENT CARD -->
    <% end %> <!-- FIN ITERATION CARD AUTOMATIQUE-->
  </div> <!-- FIN 2E COLONNE -->
</div> <!-- div class bookings-global-container -->

animals_rent/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airbnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/9bb344ad6f.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <% unless params[:action] == 'home' %>
      <%= render "components/navbar" %>
    <% end %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= render "components/footer" %>
  </body>
</html>

animals_rent/app/views/owner/animals/index.html.erb
<div class="container">
  <div class="card-rent">
    <h3>The creatures that I will praise</h3>
      <div class="card-rent-list">
        <ul>
          <li></li>
          <li></li>
          <li></li>
          <li></li>
          <li></li>
          <li></li>
          <li></li>
          <li></li>
        </ul>

      </div>

  </div>


</div>

animals_rent/app/views/owner/animals/new.html.erb
<div class="container-create-form">

  <h1 class="title-create"><strong>Add a beast</strong></h1>
  <div class="form-create">
    <%= simple_form_for [:owner, @animal] do |f| %>
      <%= f.input :name, label: "Name of your beast" %>
      <%= f.input :price_per_day, label: "Price per day ?" %>
      <%= f.input :localisation, label: 'Where find it ?' %>
      <%= f.input :can_swim, label: 'Did it swim ?' %>
      <%= f.input :can_walk, label: 'Did it walk ?' %>
      <%= f.input :can_fly, label: 'Did it fly ?' %>
      <%= f.input :summary, label: 'A short description :' %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "Add your beast", class:'button-create-animal' %>
    <% end %>
  </div>

</div>

animals_rent/app/views/pages/home.html.erb
    <%= render "components/banner" %>